### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by ivanperez-keera** [keera-studios/Haskelloids#1]
It would be great to have a readme for this project.

A good template is here:
https://github.com/ivanperez-keera/SpaceInvaders/blob/develop/README.md

It would be important to be careful as the author name, project name, and screenshot are completely different.

**Comment by mrehayden1** [comment]
I've put some basic installation instructions in #20 as a bare minimum.

**Comment by myroslambda** [comment]
Ok. Closed for now, will introduce other instruction requests in different issues. Thanks!
