### ISSUE TITLE
Cabal file update hompage information

### ISSUE THREAD

**Issue by chriz-zeller** [keera-studios/Haskelloids#11]
In the cabal file the following line needs to be updated:
https://github.com/keera-studios/Haskelloids/blob/eb571151815ae2cadcd1e3271b928f30610872a0/Haskelloids.cabal#L19
The homepage should be: https://github.com/keera-studios/Haskelloids

**Comment by caro401** [comment]
Hi! I'd like to work on this issue please

**Comment by chriz-zeller** [comment]
Thank you, @caro401! :)
