### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by chriz-zeller** [keera-studios/Haskelloids#13]
Installation error due to changes in hmatrix package.

The "Numeric.LinearAlgebra.Interface" is only available until version 0.9.3.0.

However, with this hmatrix version, a dependency on haskell98 would be needed, but that's not included in hmatrix's own cabal file.

**Comment by ivanperez-keera** [comment]
Error log:

https://travis-ci.org/keera-studios/Haskelloids/jobs/291160391
