### ISSUE TITLE
Add stack.yaml

### ISSUE THREAD

**Issue by vrom911** [keera-studios/Haskelloids#14]
So stack users also can build the project

**Comment by ivanperez-keera** [comment]
Sounds great. Do you know how to do it?

**Comment by ivanperez-keera** [comment]
This project is currently broken due to a library having changed much. The original author is looking into it.

However: https://github.com/ivanperez-keera/haskanoid/issues/25.

**Comment by ivanperez-keera** [comment]
To be more precise: this package depends on `hmatrix<0.10`, which only installs with older versions of GHC because it uses haskell 98 stuff without depending on the library `haskell98`.

**Comment by vrom911** [comment]
Yes, I also came up to the same problem with versioning. I will follow the corresponding issues  you mentioned as well, thank you!

**Comment by mrehayden1** [comment]
Fixed #20
