### ISSUE TITLE
Missing bang patterns

### ISSUE THREAD

**Issue by myroslambda** [keera-studios/Haskelloids#24]
The following two files use Bang Patterns but do not declare the extension.
```
src/Haskelloids/Object/Asteroid.hs
src/Haskelloids/Object/Bullet.hs
```

@mrehayden1 Could you please send this in a separate PR forking off the current master in keera-studios/Haskelloids if that error was already there?

**Comment by mrehayden1** [comment]
Okay, however why don't we move all GHC extension flags to a build file?
