### ISSUE TITLE
Turn OPTIONS_GHC into LANGUAGE pragmas

### ISSUE THREAD

**Issue by ivanperez-keera** [keera-studios/Haskelloids#4]
This implementation uses OPTIONS_GHC to specify language extensions (you can search for it in the file).

There are newer ways of doing this now: https://downloads.haskell.org/~ghc/7.2.1/docs/html/users_guide/pragmas.html#language-pragma

**Comment by hit023** [comment]
Hey @ivanperez-keera , you mean replacing each occurence in the repo with alternatives of this format:
`{-# LANGUAGE ForeignFunctionInterface, CPP #-}` ?

**Comment by ivanperez-keera** [comment]
Exactly!

**Comment by myroslambda** [comment]
Closed by #18
